### ISSUE TITLE
Can't install via BRAT

### ISSUE THREAD

**Issue by DitchComfort** [RafaelGB/obsidian-bd-folder#8]
I can't install via BRAT. main.js or something is missing…?

**Comment by RafaelGB** [comment]
At the moment it is only possible to install it manually by downloading the binary files of the latest release tag (currently v0.0.4).

Currently this project is in beta. I estimate that I will request to upload it officially next month.

I don't know the BRAT download method. Could you give an example?

**Comment by pastorjack** [comment]
I had the same problem. This is what he is referencing: https://github.com/TfTHacker/obsidian42-brat

**Comment by RafaelGB** [comment]
thanks for the link. I will try it and fix it, brat its a nice plugin btw! didnt know about it

**Comment by RafaelGB** [comment]
Fixed renaming tag format of versions for 'vx.y.z' to 'x.y.z'

Reading the docs of the plugin looks like frozen versions supports all kind of names but auto version just the standard ones x.y.z

Could you confirm it to close this issue? hope this helps =)

**Comment by reidpat** [comment]
Still not working for me. Same error as @DitchComfort above.

**Comment by RafaelGB** [comment]
Okey, not I saw the REAL problem. I was updating my manifest after releases with next version on main branch & BRAT plugin use the version inside that manifest to know witch one is the lastest.

Knowning this, I will leave the lastest version released in that file to support that plugin.

Thanks for your report! 
<img width="586" alt="Screenshot 2022-04-24 at 09 18 00" src="https://user-images.githubusercontent.com/11924043/164964842-0bd1afd8-1898-4738-9af6-3f1466a8491b.png">

**Comment by RafaelGB** [comment]
I recieved confirmation about the fix of this issue. It is listed as closed.

**Comment by DitchComfort** [comment]
Thank you
